ci:
  autofix_commit_msg: "🚨 `pre-commit-ci`修复格式错误"
  autofix_prs: true
  autoupdate_branch: v4-nonebot2
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "⬆️ `pre-commit-ci`自动升级"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
