[project]
name = "nonebot-plugin-genshinuid"
version = "6.0.0"
description = "支持OneBot(QQ)、OneBotV12、QQ频道、Telegram（电报）、FeiShu（飞书）、Discord的全功能NoneBot2原神插件"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.10,<4"
authors = [
    { name = "KimigaiiWuyi", email = "444835641@qq.com" },
]
dependencies = [
    "nonebot2>=2.0.0b4",
    "pillow>=9.2.0",
    "msgspec>=0.13.1",
    "aiofiles>=23.1.0",
    "websockets>=11.0.1",
    "nonebot-plugin-apscheduler>=0.2.0",
    "aiohttp>=3.9.3",
    "nonebot-plugin-alconna>=0.57.0",
]

[project.urls]
Homepage = "https://github.com/KimigaiiWuyi/GenshinUID/tree/v4.0-nonebot2"
Repository = "https://github.com/KimigaiiWuyi/GenshinUID"
Documentation = "https://docs.gsuid.gbots.work/#/"
"Bug Tracker" = "https://github.com/KimigaiiWuyi/GenshinUID/issues"

[project.optional-dependencies]
dev = [
    "ruff>=0.14.7",
    "pre-commit>=2.21.0",
    "pyright>=1.1.350",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["GenshinUID"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "standard"
include = ["GenshinUID"]
exclude = ["dist", "docs"]
disableBytesTypePromotions = false
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false

[tool.basedpyright]
deprecateTypingAliases = false
