[project]
name = "GenshinUID"
version = "7.0.0"
description = "基于GsCore的原神面板查询/原神Wiki/米社签到/树脂提醒插件"
authors = [{ name = "KimigaiiWuyi", email = "444835641@qq.com" }]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "httpx>=0.23.0",
    "beautifulsoup4>=4.11.1",
    "lxml>=4.9.2",
]

[project.urls]
Homepage = "https://github.com/KimigaiiWuyi/GenshinUID/tree/v4"
Repository = "https://github.com/KimigaiiWuyi/GenshinUID"
Documentation = "https://github.com/KimigaiiWuyi/GenshinUID/wiki"
"Bug Tracker" = "https://github.com/KimigaiiWuyi/GenshinUID/issues"
