TEST_SEQ = [
    {'char': '达达利亚', 'action': 'A满蓄力瞄准射击', 'type': '伤害'},
    {'char': '枫原万叶', 'action': 'E长按伤害', 'type': '伤害'},
    {'char': '枫原万叶', 'action': 'Q斩击伤害', 'type': '伤害'},
    {'char': '枫原万叶', 'action': 'Q持续伤害', 'type': '持续'},
    {'char': '班尼特', 'action': 'E点按伤害', 'type': '伤害'},
    {'char': '班尼特', 'action': 'Q伤害', 'type': '伤害'},
    {'char': '香菱', 'action': 'E喷火伤害', 'type': '持续'},
    {'char': '香菱', 'action': 'Q旋火轮伤害', 'type': '持续'},
    {'char': '达达利亚', 'action': 'E状态激发伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'E一段伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'E重击伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'E一段伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'E重击伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'E一段伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'E重击伤害', 'type': '伤害'},
    {'char': '达达利亚', 'action': 'Q伤害·近战', 'type': '伤害'},
]
