AMBR_EVENT_URL = 'https://api.ambr.top/assets/data/event.json'
AMBR_CHAR_URL = 'https://api.ambr.top/v2/chs/avatar/{}?vh=32F2'
AMBR_WEAPON_URL = 'https://api.ambr.top/v2/CHS/weapon/{}?vh=32F6'
AMBR_BOOK_URL = 'https://api.ambr.top/v2/chs/book?vh=34F5'
AMBR_BOOK_DETAILS_URL = 'https://api.ambr.top/v2/CHS/book/{}?vh=34F5'
AMBR_BOOK_DATA_URL = 'https://api.ambr.top/v2/CHS/readable/Book{}?vh=34F5'
