name: Unittest

on:
  push:
    branches:
      - nonebot2-beta1
  pull_request:


jobs:
  test:
    name: Test
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry
        shell: bash

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          architecture: "x64"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with test --without dev
        shell: bash

      - name: Run Pytest
        run: |
          cd tests
          poetry run pytest
